### ISSUE TITLE
ERR Error running script (user_script:34: Bad data format in input.)

### ISSUE THREAD

**Issue by xanview** [soveran/ohm#208]
I am getting this exception:

```
/usr/local/lib/ruby/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1313:in `save': ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input.  (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1377:in `update'
	from /data/deployer/timeagent/app/models/device.rb:28:in `block in find_or_create'
	from /data/deployer/timeagent/app/models/device.rb:24:in `each'
	from /data/deployer/timeagent/app/models/device.rb:24:in `find_or_create'
	from /data/deployer/timeagent/app/models/time_box.rb:38:in `block in network_scan'
	from /data/deployer/timeagent/app/models/time_box.rb:35:in `each'
	from /data/deployer/timeagent/app/models/time_box.rb:35:in `network_scan'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:138:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:104:in `runner'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

When trying to run:

```ruby
>>> params = {:interface=>"eth0", :mac=>"04:F0:21:20:2A:FB", :vendor=>"Compex Systems Pte", :snmp=>true, :_type=>"Wireless", :online=>1, :product_family=>"fireFlyPTP", :ssid=>"FFlink", :channel_number=>"36", :rf_power=>"0", :mode=>"0", :rf_channel=>5180}
>>> d = Device.first
>>>  params.each {|key, value| d.update(key => value) }
```

The first few values update without issues, but then the remaining ones all fail. This works on my Macbook Pro but throws an exception on the Raspberry Pi. Any ideas?

**Comment by soveran** [comment]
Hey @xanview, sadly I don't own a Raspberry Pi so I can't try it myself. Which version of Redis are you running?

**Comment by xanview** [comment]
I'm running: Redis server v=2.8.19 sha=00000000:0 malloc=jemalloc-3.6.0 bits=32 build=665519ce00ddac9b

Any ideas what possible things could trigger such an error? - there is no bad format in the input. Any suggestions how to troubleshoot?

**Comment by soveran** [comment]
One idea would be to try to reduce the test case as much as possible. For example, what happens if you use a model with just one attribute and try to update it? You can try with the different params, one by one, and detect which one is failing (or maybe they all fail, but we have to find out). Once we have the problem isolated we can check what is the server receiving. Let me know what you find.

**Comment by xanview** [comment]
I tried to do a begin/rescue block with some more logging and it's throwing this:

```
Creating Wireless with: 04:F0:21:20:2A:FB
Updating 'interface' to 'eth0' (04:F0:21:20:2A:FB)
Updating 'mac' to '04:F0:21:20:2A:FB' (04:F0:21:20:2A:FB)
Updating 'vendor' to 'Compex Systems Pte' (04:F0:21:20:2A:FB)
Updating 'snmp' to 'true' (04:F0:21:20:2A:FB)
Updating '_type' to 'Wireless' (04:F0:21:20:2A:FB)
Updating 'online' to '1' (04:F0:21:20:2A:FB)
Failed to update 'product_family' to 'fireFlyPTP' (04:F0:21:20:2A:FB)
Failed to update 'version' to 'fireFlyPTP v1.86_b151120_01.00' (04:F0:21:20:2A:FB)
Failed to update 'ssid' to 'FFlink' (04:F0:21:20:2A:FB)
Failed to update 'channel_number' to '36' (04:F0:21:20:2A:FB)
Failed to update 'rf_power' to '0' (04:F0:21:20:2A:FB)
Failed to update 'mode' to '0' (04:F0:21:20:2A:FB)
Failed to update 'rf_channel' to '5180' (04:F0:21:20:2A:FB)
```

If I run Wireless.find(mac: '04:F0:21:20:2A:FB').update(mode: '0') for example in a separate process, that works without issues. But if I run that as part of the loop, it doesn't - very very strange.

**Comment by soveran** [comment]
Which version of msgpack are you using?

**Comment by xanview** [comment]
msgpack (0.7.4)

**Comment by soveran** [comment]
I just ran the tests with msgpack 0.7.4 and it works fine, but I'm wondering if we are missing something. Can you try with msgpack 0.6.2 instead to see if it works?

**Comment by soveran** [comment]
Also there was a patch to lua-msgpack from 2015 that wasn't available at the time of Redis 2.8.19. Can you update you Redis server?

**Comment by xanview** [comment]
Same exception with msgpack 0.6.2 - will try updating Redis.

**Comment by xanview** [comment]
Same exception with Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=32 build=b20071b74c2d294c

:( - tearing my hair out a little trying to figure out what is going on.

**Comment by soveran** [comment]
OK, can you try with a very simple model and see what happens? If you find a simple case that reliably reproduces that error, copy the model here so I can check it.

**Comment by xanview** [comment]
I have 2 identical models, one "Device" and one "Wireless", the latter is identical to the former with a few extra attributes. For some reason it fails, but the "Device" one does not. This is the diff between them:

```diff
1c1
< class Device < Ohm::Model
---
> class Wireless < Ohm::Model
104a105,142
> 
>   attribute :ssid
>   attribute :identifier
>   attribute :rf_channel
>   attribute :link
>   attribute :units_in_network
>   attribute :mode
>   attribute :throughput
>   attribute :rf_power
>   attribute :rssi
> 
>   attribute :product_family
>   attribute :product_id
>   attribute :version
> 
>   attribute :online
>   attribute :channel_number
>   attribute :noise_floor
>   attribute :link_rx_rate
>   attribute :link_tx_rate
>   attribute :channel_quality
```

I'm going to keep trying to figure out what is happening. Will update if I make any progress!

**Comment by xanview** [comment]
I found something that I am able to reproduce in development:

```
[32] pry(main)> device = Wireless.find(mac: "08:B4:CF:05:02:EC").first      
[:ssid, "SC-WS300"]
[:rf_channel, "5180"]
[:link, "1"]
[:units_in_network, "1"]
[:mode, "2"]
[:throughput, "0"]
[:rf_power, "1"]
[:rssi, "-96"]
[:product_family, "scorpion"]
[:product_id, "1"]
[:online, "1"]
[:channel_number, "0"]
[:noise_floor, "-95"]
[:link_rx_rate, "0"]
[:link_tx_rate, "0"]
[:channel_quality, "94"]
=> #<Wireless:0x3fd50aebcb9c>
[33] pry(main)> p "Ch Quality #{device.channel_quality}"      
"Ch Quality 94"
=> "Ch Quality 94"
[34] pry(main)> device.update :last_seen_epoch => Time.now.to_i      
[:ssid, "SC-WS300"]
[:rf_channel, "5180"]
[:link, "1"]
[:units_in_network, "1"]
[:mode, "2"]
[:throughput, "0"]
[:rf_power, "1"]
[:rssi, "-96"]
[:product_family, "scorpion"]
[:product_id, "1"]
[:online, "1"]
[:channel_number, "0"]
[:noise_floor, "-95"]
[:link_rx_rate, "0"]
[:link_tx_rate, "0"]
[:channel_quality, "94"]
[:last_seen_epoch, 1456399592]
=> #<Wireless:0x3fd50aebcb9c>
[35] pry(main)> device = Wireless.find(mac: "08:B4:CF:05:02:EC").first      
=> nil
[36] pry(main)> p "Ch Quality #{device.channel_quality}"      
NoMethodError: undefined method `channel_quality' for nil:NilClass
from (pry):31:in `<main>'
```

Any ideas what is going on there? -- the data just vanishes when I update an attribute.

**Comment by soveran** [comment]
Can you show me the code where you define the `Wireless` model?

**Comment by xanview** [comment]
Currently I have this:

Device model:

```ruby
class Device < Ohm::Model
  attribute :mac
  index :mac

  # NMAP Stuff
  attribute :vendor
  attribute :snmp # Boolean
  set :open_ports_set, :Device_Port
  set :hostnames_set, :Device_Hostname

  # All
  attribute :last_seen_epoch # Seconds Since Epoch
  attribute :interface
  attribute :_type
  set :ips_set, :Device_IP
end

#
# The following are not used directly, it's just how Ohm/Redis works:
#

# Used in Device#ips
class Device_IP < Ohm::Model
  def self.find_or_create(ip)
    self.find(ip: ip).first || self.create(ip: ip)
  end

  attribute :ip
  index :ip
end

# Used in Device#open_ports
class Device_Port < Ohm::Model
  def self.find_or_create(port)
    self.find(port: port).first || self.create(port: port)
  end

  attribute :port
  index :port
end

# Used in Device#hostnames
class Device_Hostname < Ohm::Model
  def self.find_or_create(hostname)
    self.find(hostname: hostname).first || self.create(hostname: hostname)
  end

  attribute :hostname
  index :hostname
end
```

Wireless model:

```ruby
class Wireless < Device
  # Required for find to work
  index :mac
  index :ssid

  attribute :ssid
  attribute :identifier
  attribute :rf_channel
  attribute :link
  attribute :units_in_network
  attribute :mode
  attribute :throughput
  attribute :rf_power
  attribute :rssi

  attribute :product_family
  attribute :product_id
  attribute :version

  attribute :online
  attribute :channel_number
  attribute :noise_floor
  attribute :link_rx_rate
  attribute :link_tx_rate
  attribute :channel_quality
end
```

**Comment by soveran** [comment]
I never use inheritance with Ohm models, and my guess is that what you are experiencing may be related to that fact. Do you have code that I can use to create the models and trigger the error?

**Comment by xanview** [comment]
I changed the code not to use inheritence and getting the same exception on all the wireless fields :( - The code now is:

Devices
```ruby
class Device < Ohm::Model
  attribute :mac
  index :mac

  reference :wireless, :Wireless

  # NMAP Stuff
  attribute :vendor
  attribute :snmp # Boolean
  set :open_ports_set, :Device_Port
  set :hostnames_set, :Device_Hostname

  # All
  attribute :_type
  attribute :last_seen_epoch # Seconds Since Epoch
  attribute :online
  attribute :interface

  set :ips_set, :Device_IP

  def self.find_or_create(mac, params={})
    params = params.with_indifferent_access

    device = find(mac: mac).first || create(mac: mac)
    device.update(last_seen_epoch: Time.now.to_i)

    # Update Device Attributes
    params.each do |key, value|
      next unless attributes.include? key.to_sym
      Rails.logger.info "Updating '#{key}' to '#{value.to_s}'"
      device.update(key.to_sym => value.to_s)
    end

    # Update Wireless Attributes
    if params[:_type] == "Wireless"
      Rails.logger.info "Wireless device detected"

      unless device.wireless
        device.update(wireless: Wireless.create(device: device))
      end

      params.each do |key, value|
        next unless Wireless.attributes.include? key.to_sym
        begin
          Rails.logger.info "Updating Wireless' #{key}' to '#{value.to_s}'"
          device.wireless.update(key.to_sym => value.to_s)
        rescue
          Rails.logger.warn "Failed to update Wireless '#{key}' to '#{value}'"
          # raise
        end
      end
    end

    params.delete(:hostnames)&.each do |h|
      device.hostnames_set.add Device_Hostname.find_or_create(h)
    end

    params.delete(:open_ports)&.each do |p|
      device.open_ports_set.add Device_Port.find_or_create(p)
    end

    params.delete(:ips)&.each do |ip|
      device.ips_set.add Device_IP.find_or_create(ip)
    end
    device
  end

  private

  def self.update_from_devices(devices)
    devices.each {|mac, data| find_or_create(mac, data) }
  end

end

#
# The following are not used directly, it's just how Ohm/Redis works:
#

# Used in Device#ips
class Device_IP < Ohm::Model
  def self.find_or_create(ip)
    self.find(ip: ip).first || self.create(ip: ip)
  end

  attribute :ip
  index :ip
end

# Used in Device#open_ports
class Device_Port < Ohm::Model
  def self.find_or_create(port)
    self.find(port: port).first || self.create(port: port)
  end

  attribute :port
  index :port
end

# Used in Device#hostnames
class Device_Hostname < Ohm::Model
  def self.find_or_create(hostname)
    self.find(hostname: hostname).first || self.create(hostname: hostname)
  end

  attribute :hostname
  index :hostname
end
```

Wireless:
```
class Wireless < Ohm::Model
  reference :device, :Device

  attribute :ssid
  index :ssid

  attribute :identifier
  attribute :rf_channel
  attribute :link
  attribute :units_in_network
  attribute :mode
  attribute :throughput
  attribute :rf_power
  attribute :rssi

  attribute :product_family
  attribute :product_id
  attribute :version

  attribute :channel_number
  attribute :noise_floor
  attribute :link_rx_rate
  attribute :link_tx_rate
  attribute :channel_quality
end
```

Something very strange is going on :(

**Comment by soveran** [comment]
Can you paste the code where you create the instances?

**Comment by xanview** [comment]
Sure, 

When I run the code, it throws the exception:
```
$ bundle exec rails runner 'Device.update_from_devices Lan.find_hosts'
/usr/local/lib/ruby/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1313:in `save': ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input.  (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1377:in `update'
	from /data/deployer/timeagent/app/models/device.rb:48:in `block in find_or_create'
	from /data/deployer/timeagent/app/models/device.rb:44:in `each'
	from /data/deployer/timeagent/app/models/device.rb:44:in `find_or_create'
	from /data/deployer/timeagent/app/models/device.rb:141:in `block in update_from_devices'
	from /data/deployer/timeagent/app/models/device.rb:141:in `each'
	from /data/deployer/timeagent/app/models/device.rb:141:in `update_from_devices'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:138:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:104:in `runner'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

The Lan.find_hosts method returns this:
```
$ bundle exec rails runner 'p Lan.find_hosts'
{"00:0F:FC:24:D3:85"=>{:ips=>["192.168.88.14"], :interface=>"eth0", :open_ports=>[23, 80, 554], :hostnames=>[], :mac=>"00:0F:FC:24:D3:85", :vendor=>"Merit Li-Lin Ent.", :rtsp_port=>554, :_type=>"Camera"}, "C0:3F:D5:64:AF:28"=>{:ips=>["192.168.88.101", "192.168.14.100", "10.10.1.197", "192.168.0.88", "192.168.90.100"], :interface=>"eth0", :open_ports=>[22, 80], :hostnames=>[], :mac=>"C0:3F:D5:64:AF:28", :vendor=>"Elitegroup Computer Systems Co."}, "F8:72:EA:78:AE:CF"=>{:ips=>["192.168.14.10"], :interface=>"eth0", :open_ports=>[22, 23], :hostnames=>[], :mac=>"F8:72:EA:78:AE:CF", :vendor=>"Cisco"}, "00:0C:C1:05:E8:3F"=>{:ips=>["192.168.14.96"], :interface=>"eth0", :open_ports=>[80], :hostnames=>[], :mac=>"00:0C:C1:05:E8:3F", :vendor=>"Cooper Industries"}, "B4:18:D1:DD:48:65"=>{:ips=>["192.168.14.103"], :interface=>"eth0", :open_ports=>[], :hostnames=>[], :mac=>"B4:18:D1:DD:48:65", :vendor=>"Apple", :snmp=>true}, "04:F0:21:20:2A:FB"=>{:ips=>["10.10.1.10"], :interface=>"eth0", :open_ports=>[22, 23, 80], :hostnames=>[], :mac=>"04:F0:21:20:2A:FB", :vendor=>"Compex Systems Pte", :snmp=>true, :_type=>"Wireless", :online=>1, :product_family=>"fireFlyPTP", :version=>"fireFlyPTP v1.86_b151120_01.00", :ssid=>"FFlink", :channel_number=>"36", :rf_power=>"0", :mode=>"0", :rf_channel=>5180}, "00:03:E8:02:FE:BE"=>{:ips=>["10.10.1.11"], :interface=>"eth0", :open_ports=>[23], :hostnames=>[], :mac=>"00:03:E8:02:FE:BE", :vendor=>"Wavelength Digital Limited", :_type=>"Wireless", :online=>0, :ssid=>"Wavesight", :rf_channel=>"5260", :link=>"1", :units_in_network=>"1", :mode=>"2", :throughput=>"6408", :rf_power=>"17", :rssi=>"0"}, "08:B4:CF:05:02:EC"=>{:ips=>["10.10.1.21"], :interface=>"eth0", :open_ports=>[22, 23, 80, 443], :hostnames=>[], :mac=>"08:B4:CF:05:02:EC", :vendor=>"Abicom International", :snmp=>true, :_type=>"Wireless", :online=>1, :ssid=>"SC-WS300", :rf_channel=>"5180", :link=>"1", :units_in_network=>"1", :mode=>"2", :throughput=>"0", :rf_power=>"1", :rssi=>"-96", :product_family=>"scorpion", :product_id=>"1", :channel_number=>"0", :noise_floor=>"-95", :link_tx_rate=>"0", :link_rx_rate=>"0", :channel_quality=>"94"}, "FC:99:47:3D:B5:78"=>{:open_ports=>[], :hostnames=>[], :mac=>"FC:99:47:3D:B5:78", :vendor=>"Cisco", :ips=>["192.168.14.1"]}}
```

**Comment by soveran** [comment]
Can you show me the code that you run? I'm interested in something I can copy to a file, execute, and get the same result you get.

**Comment by xanview** [comment]
Oooooh, I made some progress. I managed to reproduce in the command line and then it showed:

```
/home/deployer/.bundler/ruby/2.3.0/ws-discovery-ca794f56dfb3/lib/ws_discovery.rb:57:in `stop': eventmachine not initialized: evma_stop_machine (RuntimeError)
```

I think maybe this is somehow caused by EventMachine misbehaving in another gem? - since I cannot reproduce it all by isolating it at all, it only happens after doing a network scan.

Ohm doesn't use EM or anything like that though does it?- Any thoughts on the above?

**Comment by soveran** [comment]
No, Ohm doesn't use EM at all.

**Comment by xanview** [comment]
That was a red herring, have a look at this:

```
time-agent(prod)> device
=> {:ips=>["10.10.1.10"], :interface=>"eth0", :open_ports=>[22, 23, 80], :hostnames=>[], :mac=>"04:F0:21:20:2A:FB", :vendor=>"Compex Systems Pte", :snmp=>true, :_type=>"Wireless", :online=>1, :ssid=>"FFlink", :channel_number=>"36", :rf_power=>"0", :mode=>"0", :rf_channel=>5180}
```

So now if I try to write it, it throws an exception:

```
time-agent(prod)> Device.find_or_create('04:F0:21:20:2A:FB', device)
RuntimeError: ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input. 
	from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1313:in `save'
	from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1377:in `update'
	from /data/deployer/timeagent/app/models/device.rb:48:in `block in find_or_create'
	from /data/deployer/timeagent/app/models/device.rb:44:in `each'
	from /data/deployer/timeagent/app/models/device.rb:44:in `find_or_create'
	from (irb):32
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console.rb:65:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console_helper.rb:9:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

However, if I just copy paste the hash and create a new hash like this:

```
device2 = {:ips=>["10.10.1.10"], :interface=>"eth0", :open_ports=>[22, 23, 80], :hostnames=>[], :mac=>"04:F0:21:20:2A:FB", :vendor=>"Compex Systems Pte", :snmp=>true, :_type=>"Wireless", :online=>1, :ssid=>"FFlink", :channel_number=>"36", :rf_power=>"0", :mode=>"0", :rf_channel=>5180}
=> {:ips=>["10.10.1.10"], :interface=>"eth0", :open_ports=>[22, 23, 80], :hostnames=>[], :mac=>"04:F0:21:20:2A:FB", :vendor=>"Compex Systems Pte", :snmp=>true, :_type=>"Wireless", :online=>1, :ssid=>"FFlink", :channel_number=>"36", :rf_power=>"0", :mode=>"0", :rf_channel=>5180}
```

Then it creates the device without issues!

```
time-agent(prod)> Device.find_or_create('04:F0:21:20:2A:FB', device2)
=> #<Device:0x00000006a91db0 @attributes={:mac=>"04:F0:21:20:2A:FB", :wireless_id=>"1", :vendor=>"Compex Systems Pte", :snmp=>"true", :_type=>"Wireless", :last_seen_epoch=>1456428863, :online=>"1", :interface=>"eth0"}, @_memo={:wireless=>#<Wireless:0x00000006a7c5f0 @attributes={:device_id=>"5", :ssid=>"FFlink", :rf_channel=>"5180", :mode=>"0", :rf_power=>"0", :product_family=>"fireFlyPTP", :version=>"fireFlyPTP v1.86_b151120_01.00", :channel_number=>"36"}, @_memo={}, @id="1">}, @id="5">
```

What the hell is going on? :/

**Comment by xanview** [comment]
I found a slightly cleaner solution:

```ruby
?> p device[:product_family]
"fireFlyPTP"
=> "fireFlyPTP"
?> Device.all[5].wireless.update(product_family: device[:product_family])
RuntimeError: ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input. 
	from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1313:in `save'
	from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1377:in `update'
	from (irb):43
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console.rb:65:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console_helper.rb:9:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
?> Device.all[5].wireless.update(product_family: device[:product_family].encode("iso-8859-1").force_encoding("utf-8"))
=> #<Wireless:0x000000057dd228 @attributes={:device_id=>"5", :ssid=>"FFlink", :rf_channel=>"5180", :mode=>"0", :rf_power=>"0", :product_family=>"fireFlyPTP", :version=>"fireFlyPTP v1.86_b151120_01.00", :channel_number=>"36"}, @_memo={}, @id="1">
```

**Comment by soveran** [comment]
What I need is a way to reproduce the error. That is, file with a test case that I can run locally, see how it fails and investigate how to fix it. Can you give me the code to replicate the error? You don't have to write a test case or anything like that, just the model definitions, the model instantiation and anything you do afterwards that triggers the error.

**Comment by xanview** [comment]
Any ideas how? -- I tried to save to a file. Just the process of saving the string to a file and reading the same string back resolves the problem:

```ruby
>> Device.all[5].wireless.update(product_family: s)
RuntimeError: ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input. 
  from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1313:in `save'
  from /var/lib/gems/2.3.0/gems/ohm-2.2.0/lib/ohm.rb:1377:in `update'
  from (irb):27
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console.rb:65:in `start'
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/console_helper.rb:9:in `start'
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/command.rb:20:in `run'
  from /var/lib/gems/2.3.0/gems/railties-5.0.0.beta2/lib/rails/commands.rb:19:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'

>> open('asd.txt', 'w') {|f| f.write(s); f.close}
=> nil
>> s = open('asd.txt', 'r').read
=> "fireFlyPTP"

>> Device.all[5].wireless.update(product_family: s)
=> #<Wireless:0x00000004674c70 @attributes={:device_id=>"5", :ssid=>"FFlink", :rf_channel=>"5180", :mode=>"0", :rf_power=>"0", :product_family=>"fireFlyPTP", :version=>"fireFlyPTP v1.86_b151120_01.00", :channel_number=>"36"}, @_memo={}, @id="1">
```

I don't know how to get this string over to you in a way that makes it throw the exception. The only way for you to run the exact code I am running is to read this from a radio using SNMP. Any ideas?

**Comment by StasKoval** [comment]
Got same error. With ruby 2.3 and hiredis driver - all works fine. But with jruby got error with this :token=>"5c5fdea3ef33abb1821af0d5541534b3"

`RuntimeError (ERR Error running script (call to f_d84093efbb10df1c5995c6b0e7340520973b306d): @user_script:34: user_script:34: Bad data format in input. )`
`ruby -v                                                                                                                                             
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 9-ea+110 on 9-ea+110 +jit [linux-amd64]`

**Comment by StasKoval** [comment]
found a temporary solution

` 
class Interview < Ohm::Model 
attribute :token, lambda { |x| x.to_json }`

**Comment by soveran** [comment]
@xanview @StasKoval I have a branch that uses JSON for encoding instead of msgpack. We've had a minor issue in the past with msgpack, and it was solved by locking the version required by Ohm, but in this case it looks like we can't even get a straightforward test case in place in order to reproduce the error and fixit. That got me thinking about trying with JSON instead, as it's also supported internally by Redis. Would you like to give it a try?

**Comment by xanview** [comment]
Yes please :)

**Comment by soveran** [comment]
Great, I just pushed the branch: https://github.com/soveran/ohm/tree/json

You may have to build the gem with `gem build ohm.gemspec` in order to use it. All tests pass, but we'll have to see if it solves the encoding problem you are having. Let me know how it goes!

**Comment by StasKoval** [comment]
Great, all works with branch json.

**Comment by xanview** [comment]
Working for me too! - Thank you!

**Comment by soveran** [comment]
@xanview @StasKoval Ohm 3.0.0 is out and it includes this change. Thanks a lot for reporting the error!

**Comment by xanview** [comment]
Thank you! - No issues since the change 👍

**Comment by phlegx** [comment]
Read here about the this problem and why msgpack fails with Redis: https://github.com/antirez/lua-cmsgpack/pull/44

**Comment by soveran** [comment]
@phlegx Yes, that caused the first change when we had to lock the msgpack version (https://github.com/soveran/ohm/pull/195#issuecomment-105705002). In the end I think it was better to move away from msgpack.

**Comment by phlegx** [comment]
@soveran FYI: I have opened an issue here https://github.com/antirez/lua-cmsgpack/issues/51
I need to think whether I will also gone away from it...
